- hosts: localhost
  become: true
#  pre_tasks:
#    - name: update repositories
#      apt: update_cache=yes
#      changed_when: False
  collections:
    - community.general.flatpak

  tasks:
#    - include: ./tasks/collections.yml
#    - include: ./tasks/users.yml
#    - include: ./tasks/cron.yml
    - include: ./tasks/copy_configs.yml
#    - include: ./tasks/packages.yml
    - include: ./tasks/install_rust.yml
