# TODO make sure this linking is working correctly.
- name: Delete .bashrc
  ansible.builtin.file:
    path: "/home/{{ main_user }}/.bashrc"
    state: absent

- name: Hardlink .bashrc
  become: yes
  become_user: "{{ main_user }}"
  file:
    src: $PWD/files/conf_files/.bashrc
    dest: "/home/{{ main_user }}/.bashrc"
    state: hard

- name: Hardlink .editorconfig
  become: yes
  become_user: "{{ main_user }}"
  file:
    src: $PWD/files/conf_files/.editorconfig
    dest: "/home/{{ main_user }}/.editorconfig"
    state: hard

- name: Hardlink .tmux.conf
  become: yes
  become_user: "{{ main_user }}"
  file:
    src: $PWD/files/conf_files/.tmux.conf
    dest: "/home/{{ main_user }}/.tmux.conf"
    state: hard

- name: Hardlink .zshrc
  become: yes
  become_user: "{{ main_user }}"
  file:
    src: $PWD/files/conf_files/.zshrc
    dest: "/home/{{ main_user }}/.zshrc"
    state: hard
    force: yes

- name: Hardlink topgrade.toml
  become: yes
  become_user: "{{ main_user }}"
  file:
    src: $PWD/files/conf_files/topgrade.toml
    dest: "/home/{{ main_user }}/.config/topgrade.toml"
    state: hard
    force: yes
