- name: Make sure .ssh dir exists
  file:
    path: "/home/{{ main_user }}/.ssh"
    state: directory
    
- name: Hardlink ssh config
  become: yes
  become_user: "{{ main_user }}"
  file:
    src: $PWD/files/ssh/config
    dest: "/home/{{ main_user }}/.ssh/config"
    state: hard

- name: Hardlink ssh config_personal
  become: yes
  become_user: "{{ main_user }}"
  file:
    src: $PWD/files/ssh/config_personal
    dest: "/home/{{ main_user }}/.ssh/config_personal"
    state: hard
