- name: Install packages
  become: yes
  become_user: "{{ root_user }}"
  package:
    name:
      - apt-transport-https
      - build-essential
      - ca-certificates
      - cmake
      - curl
      - direnv
      - flatpak
      - git
      - gnome-tweaks
      - gnupg-agent
      - htop
      - libcairo2-dev
      - libdbus-glib-1-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libgirepository1.0-dev
      - libxcb-xfixes0-dev
      - pkg-config
      - python3
      - python3-dev
      - python3-venv
      - python3-wheel
      - s-tui
      - snapd
      - software-properties-common
      - stress
      - timeshift
      - tmux
      - vim
      - zsh
    state: latest
