- name: Clone throttled from GitHub
  become: yes
  become_user: "{{ main_user }}"
  git:
    repo: 'https://github.com/erpalma/throttled.git'
    dest: "/home/{{ main_user }}/Documents/throttled"

- name: Install Throttled
  become: yes
  become_user: "{{ root_user }}"
  shell: "/home/{{ main_user }}/Documents/throttled/install.sh"

- name: stop thermald.service
  become: yes
  become_user: "{{ root_user }}"
  shell: systemctl stop thermald.service

- name: disable thermald.service
  become: yes
  become_user: "{{ root_user }}"
  shell: systemctl disable thermald.service

- name: mask thermald.service
  become: yes
  become_user: "{{ root_user }}"
  shell: systemctl mask thermald.service

- name: Remove thermald
  become: yes
  become_user: "{{ root_user }}"
  package:
    name:
      - thermald
    state: absent
