- name: Add fish PPA
  become: yes
  become_user: "{{ root_user }}"
  apt_repository:
    repo: ppa:fish-shell/release-3
    state: present
    
- name: Install fish
  become: yes
  become_user: "{{ root_user }}"
  package:
    name:
      - fish
    state: latest
