#   https://gist.github.com/Yatoom/1c80b8afe7fa47a938d3b667ce234559

# git clone git@github.com:vmatare/thinkfan.git
# sudo apt install libyaml-cpp-dev
# mkdir build && cd build
# ccmake ..
# cmake -D CMAKE_BUILD_TYPE:STRING=Release ..
# make
# sudo make install
# sudo -s
# echo "options thinkpad_acpi fan_control=1" > /etc/modprobe.d/thinkfan.conf
# modprobe thinkpad_acpi
# reboot

- name: Start Thinkfan service
  become: yes
  become_user: "{{ root_user }}"
  shell: service thinkfan start

# edit /etc/modules
# Add thinkpad_acpi
#     coretemp


- name: Enable thinkfan service at boot
  become: yes
  become_user: "{{ root_user }}"
  shell: systemctl enable thinkfan.service

