- name: Install alacritty
  become: yes
  become_user: "{{ main_user }}"
  command: "/home/{{ main_user }}/.cargo/bin/cargo install alacritty"

- name: Clone alactitty from GitHub
  become: yes
  become_user: "{{ main_user }}"
  git:
    repo: 'https://github.com/alacritty/alacritty.git'
    dest: "/home/{{ main_user }}/alacritty"

- name: Alacritty Terminfo
  become: yes
  become_user: "{{ root_user }}"
  shell: "tic -xe alacritty,alacritty-direct /home/{{ main_user }}/alacritty/extra/alacritty.info"

- name: Copy Alacritty.svg
  become: yes
  become_user: "{{ root_user }}"
  copy:
    src: "/home/{{ main_user }}/alacritty/extra/logo/alacritty-term.svg"
    dest: /usr/share/pixmaps/Alacritty.svg
    owner: root
    group: root
    mode: '0644'

- name: Alacritty.desktop
  become: yes
  become_user: "{{ root_user }}"
  shell: "desktop-file-install /home/{{ main_user }}/alacritty/extra/linux/Alacritty.desktop"

- name: Update desktop database
  become: yes
  become_user: "{{ root_user }}"
  shell: update-desktop-database
