- name: Snaps
  become: yes
  become_user: "{{ root_user }}"
  community.general.snap:
    name:
      - superproductivity
      - space

- name: Snaps classic
  become: yes
  become_user: "{{ root_user }}"
  community.general.snap:
    name:
      - google-cloud-sdk
      - kubectl
    classic: yes
