- name: Install alacritty
  command: ~/.cargo/bin/cargo install alacritty

- name: Clone alactitty from GitHub
  become: yes
  become_user: "{{ main_user }}"
  git:
    repo: 'https://github.com/alacritty/alacritty.git'
    dest: "/home/{{ main_user }}/alacritty"

- name: Alacritty Terminfo
  become: yes
  become_user: root
  shell: "tic -xe alacritty,alacritty-direct /home/{{ main_user }}/alacritty/extra/alacritty.info"

- name: Copy Alacritty.svg
  become: true
  become_user: root
  copy:
    src: "/home/{{ main_user }}/alacritty/extra/logo/compat/alacritty-term+scanlines.png"
    dest: /usr/share/pixmaps/Alacritty.png
    owner: root
    group: root
    mode: '0400'

- name: Alacritty.desktop
  become: yes
  become_user: root
  shell: "desktop-file-install /home/{{ main_user }}/alacritty/extra/linux/Alacritty.desktop"

- name: Update desktop database
  become: yes
  become_user: root
  shell: update-desktop-database
