- name: Snaps
  become: yes
  become_user: "{{ main_user }}"
  community.general.snap:
    name:
      - superproductivity

- name: Snaps classic
  become: yes
  become_user: "{{ main_user }}"
  community.general.snap:
    name:
      - google-cloud-sdk
      - kubectl
    classic: yes
