- name: Install packages
  package:
    name:
      - apt-transport-https
      - build-essential
      - ca-certificates
      - cmake
      - curl
      - direnv
      - flatpak
      - git
      - gnome-tweaks
      - gnupg-agent
      - htop
      - libcairo2-dev
      - libdbus-glib-1-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libgirepository1.0-dev
      - libxcb-xfixes0-dev
      - pkg-config
      - python3
      - python3-dev
      - python3-venv
      - python3-wheel
      - s-tui
      - snapd
      - software-properties-common
      - stress
      - tmux
      - vim
      - zsh
    state: latest

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install the qBittorrent flatpak
  community.general.flatpak:
    name:  org.qbittorrent.qBittorrent
    state: present

- name: Snaps
  community.general.snap:
    name:
      - superproductivity

- name: Snaps classic
  community.general.snap:
    name:
      - google-cloud-sdk
      - kubectl
    classic: yes
