- name: Install packages
  package:
    name:
      - git
      - build-essential
      - python3-dev
      - libdbus-glib-1-dev
      - libgirepository1.0-dev
      - libcairo2-dev
      - python3-venv
      - python3-wheel
      - tmux
      - vim
      - zsh
      - stress
      - s-tui
      - snapd
      - flatpak
      - gnome-tweaks
      - google-cloud-sdk
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - htop
      - alacritty
      - direnv
    state: latest

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install the qBittorrent flatpak
  community.general.flatpak:
    name:  org.qbittorrent.qBittorrent
    state: present

- name: Snaps
  community.general.snap:
    name:
      - superproductivity
