- name: Install packages
  become: yes
  become_user: "{{ root_user }}"
  package:
    name:
      - lm-sensors
      - thinkfan
    state: latest

# - name: Start Thinkfan service
#   become: yes
#   become_user: "{{ root_user }}"
#   shell: service thinkfan start

# - name: Enable thinkfan service at boot
#   become: yes
#   become_user: "{{ root_user }}"
#   shell: systemctl enable thinkfan.service

- name: Clone throttled from GitHub
  become: yes
  become_user: "{{ main_user }}"
  git:
    repo: 'https://github.com/erpalma/throttled.git'
    dest: "/home/{{ main_user }}/Documents/throttled"

- name: Install Throttled
  become: yes
  become_user: "{{ root_user }}"
  shell: "/home/{{ main_user }}/Documents/throttled/install.sh"

  # - name: stop thermald.service
  #   become: yes
  #   become_user: "{{ root_user }}"
  #   shell: systemctl stop thermald.service

- name: stop thermald.service
  become: yes
  become_user: "{{ root_user }}"
  ansible.builtin.systemd:
    state: stopped
    name: thermald.service

- name: disable thermald.service
  become: yes
  become_user: "{{ root_user }}"
  shell: systemctl disable thermald.service

- name: mask thermald.service
  become: yes
  become_user: "{{ root_user }}"
  shell: systemctl mask thermald.service

- name: Remove thermald
  become: yes
  become_user: "{{ root_user }}"
  package:
    name:
      - thermald
    state: absent

# https://github.com/uunicorn/python-validity
- name: Install packages
  become: yes
  become_user: "{{ root_user }}"
  package:
    name:
      - fprintd
    state: absent

# - name: Add python-validity PPA
#   become: yes
#   become_user: "{{ root_user }}"
#   apt_repository:
#     repo: ppa:uunicorn/open-fprintd
#     state: present

# - name: Install python-validity packages
#   become: yes
#   become_user: "{{ root_user }}"
#   package:
#     name:
#       - open-fprintd
#       - fprintd-clients
#       - python3-validity
#     state: latest
